{{- if .Values.example.enabled -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "fluentd-file-broadcast.fullname" . }}-example
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "fluentd-file-broadcast.commonlabels" . | indent 4 }}
spec:
  replicas: {{ .Values.example.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fluentd-file-broadcast.name" . }}-example
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fluentd-file-broadcast.name" . }}-example
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: example
          image: "{{ .Values.example.image.repository }}:{{ .Values.example.image.tag }}"
          imagePullPolicy: "{{ .Values.example.image.pullPolicy }}"
          args: ["tail", "-F", "/data/topics/dummy.log"]
          resources:
{{ toYaml .Values.example.resources | trim | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: "/data"
      volumes:
      - name: data
        hostPath:
          path: {{ include "fluentd-file-broadcast.fullname" . }}
    {{- with .Values.example.nodeSelector }}
      nodeSelector:
{{ toYaml . | trim | indent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: {{ include "fluentd-file-broadcast.name" . }}-example
                app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.example.tolerations }}
      tolerations:
{{ toYaml . | trim | indent 8 }}
    {{- end }}
{{- end -}}