apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fluentd-file-broadcast.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "fluentd-file-broadcast.commonlabels" . | indent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fluentd-file-broadcast.fullname" . }}
  labels:
{{ include "fluentd-file-broadcast.commonlabels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "nodes"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fluentd-file-broadcast.fullname" . }}
  labels:
{{ include "fluentd-file-broadcast.commonlabels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd-file-broadcast.fullname" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ template "fluentd-file-broadcast.fullname" . }}
  apiGroup: ""
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ include "fluentd-file-broadcast.fullname" . }}-priority
  labels:
{{ include "fluentd-file-broadcast.commonlabels" . | indent 4 }}
value: 1000000
globalDefault: false
description: "This priority class should be used for Fluentd pods only."
